language: node_js
node_js:
  - "10"

sudo: false

cache:
  directories:
  - node_modules

env:

before_script:
  - npm run lint
  
after_success:
  - cat ./coverage/lcov.info | coveralls

git:
  depth: 1